//! Helpers for converting raw JSONL log lines into SSE frames.
//!
//! The per-game SSE stream carries four payload kinds (header, event,
//! final, turn_prompt) plus a keep-alive heartbeat. Three of those
//! (header/event/final) come directly from the JSONL log and are
//! repackaged here without re-serialising. The fourth (turn_prompt) is
//! generated by [`crate::turn_coordinator::TurnCoordinator`] and
//! pre-serialised as a full `SseFrame` JSON string — this helper
//! recognises its `kind` tag and passes through the already-typed
//! payload.

use playtest_api::{SseFrame, TurnPromptPayload};
use serde_json::Value as JsonValue;

/// Parse a broadcast line and return `(tick_id, SseFrame)`.
///
/// `tick_id` is the `id:` value used on the SSE wire. For
/// `Event { tick }` lines it's the tick; for the header it's `0`, and
/// for `Final` / `TurnPrompt` it's `None` (they are not resumable via
/// `Last-Event-ID`).
///
/// # Errors
/// Returns `None` if the line is not valid JSON or lacks a recognised
/// `kind` field — callers drop such lines with a warning.
#[must_use]
pub fn line_to_sse_frame(line: &str) -> Option<(Option<u64>, SseFrame)> {
    let trimmed = line.trim();
    if trimmed.is_empty() {
        return None;
    }
    let value: JsonValue = serde_json::from_str(trimmed).ok()?;
    let kind = value.get("kind")?.as_str()?;
    match kind {
        "header" => Some((Some(0), SseFrame::Header(value))),
        "event" => {
            let tick = value.get("tick").and_then(JsonValue::as_u64);
            Some((tick, SseFrame::Event(value)))
        }
        "final" => Some((None, SseFrame::Final(value))),
        "turn_prompt" => {
            // turn_prompt lines come from TurnCoordinator pre-serialised
            // as full SseFrame JSON: `{"kind":"turn_prompt","data":{...}}`.
            // Deserialise the `data` field back into TurnPromptPayload.
            let data = value.get("data")?.clone();
            let payload: TurnPromptPayload = serde_json::from_value(data).ok()?;
            Some((None, SseFrame::TurnPrompt(payload)))
        }
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_header_with_id_zero() {
        let line = r#"{"kind":"header","schema":2,"game":"x","seed":7,"agents":[],"started_at":0,"version":"0.0.0","config_hash":""}"#;
        let (id, frame) = line_to_sse_frame(line).unwrap();
        assert_eq!(id, Some(0));
        assert!(matches!(frame, SseFrame::Header(_)));
    }

    #[test]
    fn parses_event_with_tick_id() {
        let line = r#"{"kind":"event","tick":42,"payload":{"A":1}}"#;
        let (id, frame) = line_to_sse_frame(line).unwrap();
        assert_eq!(id, Some(42));
        assert!(matches!(frame, SseFrame::Event(_)));
    }

    #[test]
    fn parses_final_with_no_id_hint() {
        let line = r#"{"kind":"final","winner":0,"reason":"Victory","scores":[121,98]}"#;
        let (id, frame) = line_to_sse_frame(line).unwrap();
        assert_eq!(id, None);
        assert!(matches!(frame, SseFrame::Final(_)));
    }

    #[test]
    fn unknown_or_malformed_line_returns_none() {
        assert!(line_to_sse_frame("").is_none());
        assert!(line_to_sse_frame("not json").is_none());
        assert!(line_to_sse_frame(r#"{"kind":"mystery"}"#).is_none());
        assert!(line_to_sse_frame(r#"{"foo":"bar"}"#).is_none());
    }
}
