//! `playtest api-schema` — dump the OpenAPI 3.1 spec of the HTTP API.
//!
//! Thin wrapper around [`playtest_server::openapi_json`]. The
//! committed `docs/openapi.json` artifact is regenerated by running
//! `cargo run -p playtest-cli -- api-schema --out docs/openapi.json`.
//! Passing `--out -` emits to stdout for ad-hoc piping.

use std::path::PathBuf;

use anyhow::{Context, Result};
use clap::Args as ClapArgs;

/// CLI flags for the `api-schema` subcommand.
#[derive(Debug, ClapArgs)]
pub struct ApiSchemaArgs {
    /// Output path. Use `-` to write to stdout.
    #[arg(long)]
    pub out: PathBuf,
}

/// Run the `api-schema` command.
///
/// # Errors
/// Propagates serialization or filesystem errors.
pub fn run(args: &ApiSchemaArgs) -> Result<()> {
    let doc = playtest_server::openapi_json();
    let mut text = serde_json::to_string_pretty(&doc)
        .context("serializing OpenAPI document to pretty JSON")?;
    // `to_string_pretty` omits a trailing newline; committed artifacts
    // and POSIX-friendly tooling want one.
    text.push('\n');

    if args.out.as_os_str() == "-" {
        use std::io::Write;
        let stdout = std::io::stdout();
        let mut handle = stdout.lock();
        handle
            .write_all(text.as_bytes())
            .context("writing OpenAPI JSON to stdout")?;
        return Ok(());
    }

    if let Some(parent) = args.out.parent()
        && !parent.as_os_str().is_empty()
        && !parent.exists()
    {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating parent directory {}", parent.display()))?;
    }

    std::fs::write(&args.out, &text)
        .with_context(|| format!("writing OpenAPI JSON to {}", args.out.display()))?;
    Ok(())
}
